Repository apache/skywalking-python, pull requests merged in 2020-12, with the labels that each got.

#95 test: make tests really run on specified Py version and deprecate 3.5 as it's EOL
  .asf.yaml
  .github/workflows/build.yaml
  tests/plugin/docker/Dockerfile.agent
  tests/plugin/docker/docker-compose.base.yml
Labels: chore, test

#93 [Fix][Plugin] sw_flask general exceptions handled
  Makefile
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/carrier.py
  skywalking/trace/context.py
  skywalking/trace/span.py
Labels: bug, plugin

#92 make @trace decorator support async functions
  skywalking/decorators.py
Labels: core, enhancement

#96 [Enhancement] optimized path trace ignore
  skywalking/agent/__init__.py
  skywalking/config.py
  skywalking/decorators.py
  skywalking/trace/context.py
  skywalking/utils/ant_matcher.py
  tests/test_ant_matcher.py
Labels: enhancement

#97 chore: polish #92, remove useless codes and minor fix to logs
  .github/workflows/build.yaml
  README.md
  skywalking/config.py
  skywalking/decorators.py
  skywalking/trace/span.py
Labels: chore

#98 [Bugfix] allow pending data to send before exit
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
Labels: bug

#99 Fix: queue.get(block=False) can raise Empty
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
Labels: bug

#101 [Plugin] add aiohttp plugin
  requirements.txt
  skywalking/__init__.py
  skywalking/plugins/sw_aiohttp.py
  tests/plugin/sw_aiohttp/__init__.py
  tests/plugin/sw_aiohttp/docker-compose.yml
  tests/plugin/sw_aiohttp/expected.data.yml
  tests/plugin/sw_aiohttp/services/__init__.py
  tests/plugin/sw_aiohttp/services/consumer.py
  tests/plugin/sw_aiohttp/services/provider.py
  tests/plugin/sw_aiohttp/test_aiohttp.py
Labels: plugin

#102 [Plugin] added pyramid plugin
  docs/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/plugins/sw_pyramid.py
  tests/plugin/sw_pyramid/__init__.py
  tests/plugin/sw_pyramid/docker-compose.yml
  tests/plugin/sw_pyramid/expected.data.yml
  tests/plugin/sw_pyramid/services/__init__.py
  tests/plugin/sw_pyramid/services/consumer.py
  tests/plugin/sw_pyramid/services/provider.py
  tests/plugin/sw_pyramid/test_plugin.py
Labels: plugin

#104 Fix: BaseExceptions not recorded as errors
  skywalking/trace/span.py
Labels: bug

#103 chore: only install extra modules when needed, bump up version
  Dockerfile
  README.md
  setup.py
  tests/plugin/docker/docker-compose.base.yml
  tests/plugin/sw_requests/test_request.py
  tests/plugin/sw_sanic/test_sanic.py
Labels: chore

#106 Make Muse ignore bugs types that were false positives.
  .muse/config.toml
Labels: chore

#107 Add changelog for 0.5.0
  .asf.yaml
  CHANGELOG.md
Labels: chore, documentation

#108 chore: switch http to https of submodule url
  .gitmodules
Labels: chore

#109 chore: fix typo in Makefile
  Makefile
Labels: chore

#111 Update doc "how to build from source"
  CONTRIBUTING.md
  docs/FAQ.md
Labels: documentation

#112 Make the contact channels clear.
  README.md
Labels: core

#113 FIX plugin sw_pymysql error when connection haven't db
  skywalking/agent/__init__.py
  skywalking/plugins/sw_pymysql.py
Labels: bug, plugin
