Repository apache/skywalking-python, pull requests merged in 2020-11, with the labels that each got.

#79 bugfix: agent cannot reconnect after server is down
  skywalking/agent/__init__.py
  skywalking/agent/protocol/grpc.py
Labels: bug, core

#80 chore: add changelog for 0.4.0 and minor refactor
  CHANGELOG.md
  skywalking/plugins/__init__.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_elasticsearch.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
Labels: chore, documentation

#81 Bump up the version to 0.4.0
  setup.py
Labels: chore

#82 Add How-to-release doc
  docs/How-to-release.md
Labels: documentation

#83 Refactor: moved exception check to Span.__exit__
  skywalking/plugins/sw_elasticsearch.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/span.py
Labels: core, enhancement

#84 [Plugin] moved Method & Url tags before requests
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
Labels: enhancement, plugin

#85 [Plugin] http servers set URL and status tags
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/span.py
  tests/plugin/sw_http/expected.data.yml
  tests/plugin/sw_http_wsgi/expected.data.yml
  tests/plugin/sw_requests/expected.data.yml
Labels: enhancement, plugin

#86 [Enhancement] Optimized fast_path_match()
  skywalking/config.py
  skywalking/plugins/__init__.py
  skywalking/utils/ant_matcher.py
Labels: enhancement

#87 Fix: Non-global skywalking logging
  skywalking/agent/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
  skywalking/client/grpc.py
  skywalking/client/http.py
  skywalking/client/kafka.py
  skywalking/loggings.py
  skywalking/plugins/__init__.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_elasticsearch.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/context.py
Labels: bug

#88 [Enhancement] Async task context support
  skywalking/agent/protocol/grpc.py
  skywalking/trace/context.py
Labels: core, enhancement

#89 [Enhancement] Async tasks should work 100%
  skywalking/trace/context.py
Labels: core, enhancement

#90 chore: stop propagating logs to avoid logging twice and adjust log format
  .github/workflows/build.yaml
  skywalking/loggings.py
Labels: chore

#91 Add sanic plugin
  docs/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_sanic.py
  tests/plugin/sw_sanic/__init__.py
  tests/plugin/sw_sanic/docker-compose.yml
  tests/plugin/sw_sanic/expected.data.yml
  tests/plugin/sw_sanic/services/__init__.py
  tests/plugin/sw_sanic/services/consumer.py
  tests/plugin/sw_sanic/services/provider.py
  tests/plugin/sw_sanic/test_sanic.py
Labels: plugin
