Repository apache/skywalking-python, pull requests merged in 2020-06, with the labels that each got.

#11 Simplify the docker context path and rename test
  tests/plugin/http/test_http.py
Labels: test

#9 Add requests plugin
  skywalking/plugins/sw_requests/__init__.py
  tests/plugin/sw_requests/__init__.py
  tests/plugin/sw_requests/docker-compose.yml
  tests/plugin/sw_requests/expected.data.yml
  tests/plugin/sw_requests/provider.py
  tests/plugin/sw_requests/test_request.py
Labels: enhancement

#13 Add missing docs of plugin requests
  .gitignore
  README.md
Labels: documentation

#14 Fix wrong operation in the inject method
  skywalking/trace/span/__init__.py
  tests/plugin/sw_http/expected.data.yml
  tests/plugin/sw_requests/expected.data.yml
Labels: bug

#15 Add some pip classifiers to be easily searched by users
  setup.py
Labels: chore

#16 Add CHANGELOG for 0.1.0 and add missing doc for `AUTHENTICATION` env var
  CHANGELOG.md
  README.md
  setup.py
Labels: chore

#19 Fix thread local context not init in Django and add upload command to Makefile
  Makefile
  skywalking/trace/context/__init__.py
Labels: bug, chore

#18 Bugfix when protocol use http, fix loop call report trigger by skywalking self http request
  skywalking/agent/__init__.py
  skywalking/plugins/sw_requests/__init__.py
Labels: bug

#21 Add docs for how to build from sources and fail the builds when flake8 fails
  Makefile
  README.md
  docs/FAQ.md
  tests/plugin/sw_http/__init__.py
  tests/plugin/sw_http_wsgi/__init__.py
  tests/plugin/sw_http_wsgi/services/provider.py
  tests/plugin/sw_requests/__init__.py
  tests/plugin/sw_requests/services/consumer.py
Labels: chore, documentation

#22 Add missing step in doc
  docs/FAQ.md
Labels: documentation

#23 Add missing dependency in release
  setup.py
Labels: chore

#24 Add Python version requirement in the doc
  README.md
Labels: documentation

#26 Rename project name to apache-skywalking
  Makefile
  setup.py
Labels: chore

#27 Add docs on how to install from Pypi
  README.md
Labels: documentation
