Repository apache/skywalking-python, pull requests merged in 2020-07, with the labels that each got.

#29 [Core][Defect] Validate carrier before using it
  skywalking/trace/carrier/__init__.py
  skywalking/trace/context/__init__.py
  skywalking/trace/segment/__init__.py
  skywalking/trace/span/__init__.py
Labels: bug

#30 [Core][BugFix] Add content equality of SegmentRef
  skywalking/trace/segment/__init__.py
Labels: bug

#32 [Doc] Add Flask plugin and fix requests plugin name
  README.md
Labels: documentation

#34 Chore: add missing `log` method and simplify test codes
  skywalking/trace/span/__init__.py
  tests/plugin/__init__.py
  tests/plugin/sw_flask/test_flask.py
  tests/plugin/sw_http/test_http.py
  tests/plugin/sw_http_wsgi/test_http_wsgi.py
  tests/plugin/sw_requests/test_request.py
Labels: chore

#33 Add component ID for requests plugin
  .gitignore
  skywalking/__init__.py
  skywalking/plugins/sw_requests/__init__.py
  tests/plugin/sw_flask/expected.data.yml
  tests/plugin/sw_requests/expected.data.yml
Labels: enhancement

#38 Created venv builders for linux/windows and req flashers + use documentation
  .gitignore
  README.md
  requirements.txt
  tools/check-license-header.py
  tools/env/build_requirements_linux.sh
  tools/env/build_requirements_windows.bat
  tools/env/setup_linux.sh
  tools/env/setup_windows.ps1
Labels: chore, documentation

#39 Add PyMsql Sql Parameters
  README.md
  skywalking/config/__init__.py
  skywalking/plugins/sw_pymysql/__init__.py
  skywalking/trace/tags/__init__.py
  tests/plugin/sw_pymysql/expected.data.yml
  tests/plugin/sw_pymysql/services/provider.py
Labels: feature, plugin

#37 Add plugin for Django Agent
  skywalking/__init__.py
  skywalking/plugins/sw_django/__init__.py
  tests/plugin/sw_django/__init__.py
  tests/plugin/sw_django/docker-compose.yml
  tests/plugin/sw_django/expected.data.yml
  tests/plugin/sw_django/services/__init__.py
  tests/plugin/sw_django/services/consumer.py
  tests/plugin/sw_django/services/provider.py
  tests/plugin/sw_django/test_django.py
Labels: feature, plugin

#40 Add ignore_suffix Config
  README.md
  skywalking/config/__init__.py
  skywalking/trace/context/__init__.py
Labels: feature

#42 add django in document.
  README.md
Labels: documentation

#44 Add Redis Plugin
  README.md
  setup.py
  skywalking/__init__.py
  skywalking/plugins/sw_redis/__init__.py
  tests/plugin/sw_redis/__init__.py
  tests/plugin/sw_redis/docker-compose.yml
  tests/plugin/sw_redis/expected.data.yml
  tests/plugin/sw_redis/services/__init__.py
  tests/plugin/sw_redis/services/consumer.py
  tests/plugin/sw_redis/services/provider.py
  tests/plugin/sw_redis/test_redispy.py
Labels: feature, plugin

#45 Update Redis plugin Component Id
  skywalking/__init__.py
  tests/plugin/sw_redis/expected.data.yml
  tests/plugin/sw_redis/test_redis.py
Labels: chore

#46 Test: print the diff list when validation failed
  setup.py
  tests/plugin/__init__.py
Labels: enhancement, test

#48 Add Tornado Plugin
  README.md
  setup.py
  skywalking/__init__.py
  skywalking/plugins/sw_tornado/__init__.py
  tests/plugin/sw_tornado/__init__.py
  tests/plugin/sw_tornado/docker-compose.yml
  tests/plugin/sw_tornado/expected.data.yml
  tests/plugin/sw_tornado/services/__init__.py
  tests/plugin/sw_tornado/services/consumer.py
  tests/plugin/sw_tornado/services/provider.py
  tests/plugin/sw_tornado/test_tornado.py
Labels: feature, plugin

#49 Enable Django collect http parameters
  README.md
  skywalking/config/__init__.py
  skywalking/plugins/sw_django/__init__.py
  tests/plugin/sw_django/expected.data.yml
  tests/plugin/sw_django/services/consumer.py
  tests/plugin/sw_django/test_django.py
Labels: feature, plugin

#51 Add changelog for 0.2.0
  CHANGELOG.md
  setup.py
  tests/plugin/sw_pymysql/docker-compose.yml
  tools/env/setup_linux.sh
Labels: chore

#52 Make plugin compatible with Django < 2.2
  skywalking/plugins/sw_django/__init__.py
Labels: enhancement, plugin

#53 Add Rabbitmq Plugin
  README.md
  setup.py
  skywalking/__init__.py
  skywalking/plugins/sw_rabbitmq/__init__.py
  tests/plugin/sw_rabbitmq/__init__.py
  tests/plugin/sw_rabbitmq/docker-compose.yml
  tests/plugin/sw_rabbitmq/expected.data.yml
  tests/plugin/sw_rabbitmq/services/__init__.py
  tests/plugin/sw_rabbitmq/services/consumer.py
  tests/plugin/sw_rabbitmq/services/producer.py
  tests/plugin/sw_rabbitmq/test_kafka.py
Labels: feature, plugin

#54 chore: add make goal to package release tar ball
  Makefile
Labels: chore
