Repository apache/skywalking-python, pull requests merged in 2020-08, with the labels that each got.

#55 Add CorrelationContext
  README.md
  skywalking/config/__init__.py
  skywalking/trace/carrier/__init__.py
  skywalking/trace/context/__init__.py
  skywalking/trace/span/__init__.py
  tests/plugin/sw_flask/services/consumer.py
  tests/plugin/sw_flask/services/provider.py
  tests/plugin/sw_flask/test_flask.py
Labels: core, feature

#36 Refactor: move __init__.py to individual file
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/interceptors.py
  skywalking/client/grpc.py
  skywalking/client/http.py
  skywalking/config.py
  skywalking/decorators.py
  skywalking/loggings.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/carrier.py
  skywalking/trace/context.py
  skywalking/trace/segment.py
  skywalking/trace/span.py
  skywalking/trace/tags.py
Labels: chore

#56 Support snapshot context
  skywalking/agent/protocol/grpc.py
  skywalking/trace/context.py
  skywalking/trace/segment.py
  skywalking/trace/snapshot.py
  tests/plugin/sw_flask/expected.data.yml
  tests/plugin/sw_flask/services/consumer.py
Labels: core, feature

#57 update test health check
  tests/plugin/sw_django/test_django.py
  tests/plugin/sw_flask/test_flask.py
  tests/plugin/sw_http/test_http.py
  tests/plugin/sw_http_wsgi/test_http_wsgi.py
  tests/plugin/sw_kafka/test_kafka.py
  tests/plugin/sw_pymysql/test_pymysql.py
  tests/plugin/sw_rabbitmq/test_kafka.py
  tests/plugin/sw_redis/docker-compose.yml
  tests/plugin/sw_redis/test_redis.py
  tests/plugin/sw_requests/docker-compose.yml
  tests/plugin/sw_requests/test_request.py
  tests/plugin/sw_tornado/test_tornado.py
Labels: test

#58 [Doc] Add dev doc and reorganize the structure
  .github/workflows/build.yaml
  CONTRIBUTING.md
  README.md
  docs/Developer.md
  docs/EnvVars.md
  docs/PluginTest.md
  docs/Plugins.md
  requirements.txt
  tools/env/build_requirements_linux.sh
  tools/env/setup_linux.sh
Labels: documentation

#59 Add trace ignore
  docs/EnvVars.md
  skywalking/config.py
  skywalking/trace/context.py
  skywalking/utils/ant_matcher.py
  tests/test_ant_matcher.py
Labels: core, feature

#60 Add plugin for PyMongo(support version 3.7.0 or above)
  docs/EnvVars.md
  docs/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_pymongo.py
  tests/plugin/sw_pymongo/__init__.py
  tests/plugin/sw_pymongo/docker-compose.yml
  tests/plugin/sw_pymongo/expected.data.yml
  tests/plugin/sw_pymongo/services/__init__.py
  tests/plugin/sw_pymongo/services/consumer.py
  tests/plugin/sw_pymongo/services/provider.py
  tests/plugin/sw_pymongo/test_pymongo.py
Labels: plugin

#61 [Chore] Add pull request template for plugin
  .github/PULL_REQUEST_TEMPLATE
  setup.py
Labels: chore

#62 Add thread propagation
  README.md
  skywalking/decorators.py
  tests/plugin/sw_flask/services/consumer.py
Labels: core, feature

#64 Add elasticsearch plugin
  docs/EnvVars.md
  docs/Plugins.md
  requirements.txt
  setup.py
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_elasticsearch.py
  tests/plugin/sw_elasticsearch/__init__.py
  tests/plugin/sw_elasticsearch/docker-compose.yml
  tests/plugin/sw_elasticsearch/expected.data.yml
  tests/plugin/sw_elasticsearch/services/__init__.py
  tests/plugin/sw_elasticsearch/services/consumer.py
  tests/plugin/sw_elasticsearch/test_elasticsearch.py
Labels: feature, plugin

#63 [Plugin] check version of packages when install plugins
  docs/Developer.md
  skywalking/plugins/__init__.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_pymongo.py
  tests/test_version_check.py
Labels: enhancement, plugin

#65 [Enhancement] add tags to decorators
  skywalking/decorators.py
Labels: core, enhancement

#71 update version
  setup.py
Labels: chore

#72 [Core][Bug] Move generated packages into skywalking namespace
  .gitignore
  MANIFEST.in
  Makefile
  skywalking/agent/protocol/grpc.py
  skywalking/client/grpc.py
  tools/codegen.py
Labels: bug, core
