Repository apache/skywalking-python, pull requests merged in 2020-05, with the labels that each got.

#1 Add 8.0 requirement in the readme.
  README.md
Labels: documentation

#2 BugFix: http.method is always PATCH
  README.md
  skywalking/__init__.py
  skywalking/plugins/sw_http/__init__.py
  skywalking/plugins/sw_request/__init__.py
  tests/main.py
Labels: bug

#3 Feature: support authentication in grpc
  skywalking/agent/protocol/grpc/__init__.py
  skywalking/agent/protocol/grpc/interceptors.py
  skywalking/config/__init__.py
Labels: feature

#5 Feature: logging level and disabling plugins
  Makefile
  README.md
  docs/FAQ.md
  setup.py
  skywalking/__init__.py
  skywalking/agent/__init__.py
  skywalking/config/__init__.py
  skywalking/loggings/__init__.py
  skywalking/plugins/__init__.py
  skywalking/plugins/sw_http_server/__init__.py
  skywalking/plugins/sw_urllib_request/__init__.py
  tests/consumer.py
  tests/provider.py
Labels: chore, documentation, enhancement

#6 Feature: report service instance to backend
  skywalking/agent/protocol/grpc/__init__.py
  skywalking/client/grpc/__init__.py
Labels: enhancement

#7 BugFix: plugin urllib.request
  skywalking/plugins/sw_urllib_request/__init__.py
  tests/consumer.py
  tests/main.py
  tests/provider.py
Labels: bug

#8 Feature: adapt HTTP protocol
  .github/workflows/build.yaml
  README.md
  setup.py
  skywalking/agent/__init__.py
  skywalking/agent/protocol/grpc/__init__.py
  skywalking/agent/protocol/http/__init__.py
  skywalking/client/grpc/__init__.py
  skywalking/client/http/__init__.py
  skywalking/config/__init__.py
Labels: feature
