Repository apache/skywalking-python, pull requests merged in 2021-09, with the labels that each got.

#160 Cleanup the release notes
  CHANGELOG.md
Labels: documentation

#161 spans correctly reference finished parents
  skywalking/trace/context.py
  skywalking/trace/span.py
Labels: enhancement

#163 fix broken url
  docs/en/setup/Installation.md
Labels: documentation

#165 Refactor SkyWalking Python to use the CLI for CI instead of legacy setup
  skywalking/bootstrap/loader/sitecustomize.py
  tests/plugin/sw_aiohttp/docker-compose.yml
  tests/plugin/sw_aiohttp/services/consumer.py
  tests/plugin/sw_aiohttp/services/provider.py
  tests/plugin/sw_django/docker-compose.yml
  tests/plugin/sw_django/services/consumer.py
  tests/plugin/sw_django/services/provider.py
  tests/plugin/sw_elasticsearch/docker-compose.yml
  tests/plugin/sw_elasticsearch/services/consumer.py
  tests/plugin/sw_falcon/docker-compose.yml
  tests/plugin/sw_falcon/services/consumer.py
  tests/plugin/sw_falcon/services/provider.py
  tests/plugin/sw_flask/docker-compose.yml
  tests/plugin/sw_flask/services/consumer.py
  tests/plugin/sw_flask/services/provider.py
  tests/plugin/sw_http/docker-compose.yml
  tests/plugin/sw_http/services/consumer.py
  tests/plugin/sw_http/services/provider.py
  tests/plugin/sw_http_wsgi/docker-compose.yml
  tests/plugin/sw_http_wsgi/services/consumer.py
  tests/plugin/sw_http_wsgi/services/provider.py
  tests/plugin/sw_kafka/docker-compose.yml
  tests/plugin/sw_kafka/services/consumer.py
  tests/plugin/sw_kafka/services/producer.py
  tests/plugin/sw_psycopg2/docker-compose.yml
  tests/plugin/sw_psycopg2/services/consumer.py
  tests/plugin/sw_psycopg2/services/provider.py
  tests/plugin/sw_pymongo/docker-compose.yml
  tests/plugin/sw_pymongo/services/consumer.py
  tests/plugin/sw_pymongo/services/provider.py
  tests/plugin/sw_pymysql/docker-compose.yml
  tests/plugin/sw_pymysql/services/consumer.py
  tests/plugin/sw_pymysql/services/provider.py
  tests/plugin/sw_pyramid/docker-compose.yml
  tests/plugin/sw_pyramid/services/consumer.py
  tests/plugin/sw_pyramid/services/provider.py
  tests/plugin/sw_rabbitmq/docker-compose.yml
  tests/plugin/sw_rabbitmq/services/consumer.py
  tests/plugin/sw_rabbitmq/services/producer.py
  tests/plugin/sw_redis/docker-compose.yml
  tests/plugin/sw_redis/services/consumer.py
  tests/plugin/sw_redis/services/provider.py
  tests/plugin/sw_requests/docker-compose.yml
  tests/plugin/sw_requests/services/consumer.py
  tests/plugin/sw_requests/services/provider.py
  tests/plugin/sw_sanic/docker-compose.yml
  tests/plugin/sw_sanic/test_sanic.py
  tests/plugin/sw_tornado/docker-compose.yml
  tests/plugin/sw_tornado/services/consumer.py
  tests/plugin/sw_tornado/services/provider.py
  tests/plugin/sw_urllib3/docker-compose.yml
  tests/plugin/sw_urllib3/services/consumer.py
  tests/plugin/sw_urllib3/services/provider.py
Labels: enhancement, test

#166 Remove places that mentions Python 3.5 support due to EOL
  README.md
  docker/Makefile
  docs/en/setup/Container.md
  docs/en/setup/Installation.md
  docs/en/setup/Plugins.md
  setup.py
Labels: chore
