Repository apache/skywalking-python, pull requests merged in 2021-07, with the labels that each got.

#125 Python celery plugin
  docs/EnvVars.md
  docs/Plugins.md
  requirements.txt
  setup.py
  skywalking/__init__.py
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/agent/protocol/http.py
  skywalking/client/http.py
  skywalking/config.py
  skywalking/plugins/sw_celery.py
  skywalking/plugins/sw_sanic.py
  skywalking/trace/context.py
  skywalking/trace/tags.py
Labels: core, enhancement, plugin

#128 removed requests as required dependency
  setup.py
Labels: dependencies

#129 fix celery origin, detect nonlocal if no sw8 head
  setup.py
  skywalking/plugins/sw_celery.py
Labels: plugin

#130 removed trace/ipc
  README.md
  skywalking/agent/protocol/grpc.py
  skywalking/trace/ipc/__init__.py
  skywalking/trace/ipc/process.py
  tests/plugin/sw_process/__init__.py
  tests/plugin/sw_process/docker-compose.yml
  tests/plugin/sw_process/expected.data.yml
  tests/plugin/sw_process/services/__init__.py
  tests/plugin/sw_process/services/consumer.py
  tests/plugin/sw_process/services/provider.py
  tests/plugin/sw_process/test_process.py
Labels: core

#131 del StackedSpan, no explicit stored SpanContext
  skywalking/trace/context.py
  skywalking/trace/span.py
Labels: enhancement

#132 explicit component inheritance
  README.md
  skywalking/plugins/sw_aiohttp.py
  skywalking/plugins/sw_celery.py
  skywalking/plugins/sw_elasticsearch.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_psycopg2.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/context.py
  skywalking/trace/span.py
Labels: enhancement, plugin

#133 Use agent test tool snapshot Docker image instead of building in CI
  tests/plugin/docker/Dockerfile.tool
  tests/plugin/docker/docker-compose.base.yml
Labels: chore

#134 Secure connection option for GRPC and HTTP
  README.md
  docs/EnvVars.md
  skywalking/agent/protocol/grpc.py
  skywalking/client/http.py
  skywalking/config.py
  skywalking/trace/context.py
Labels: core, enhancement

#136 fix trace decorator not work
  skywalking/decorators.py
Labels: bug
