Repository apache/skywalking-python, pull requests merged in 2021-08, with the labels that each got.

#139 cleanup: remove unused methods
  skywalking/config.py
  tests/plugin/sw_rabbitmq/docker-compose.yml
Labels: chore

#138 fix grpc disconnect, SW_AGENT_MAX_BUFFER_SIZE
  docs/EnvVars.md
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
  skywalking/client/grpc.py
  skywalking/config.py
  skywalking/trace/context.py
Labels: bug

#140 updated kafka protocol for recent changes
  skywalking/agent/protocol/kafka.py
Labels: bug

#141 NoopSpan on queue full, propagation downstream
  skywalking/agent/__init__.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/carrier.py
  skywalking/trace/context.py
  skywalking/trace/span.py
Labels: enhancement

#142 chore: bump up `requests` version to avoid license issue
  setup.py
Labels: chore

#143 add http ignore by method
  docs/EnvVars.md
  skywalking/config.py
  skywalking/plugins/sw_aiohttp.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_pyramid.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_sanic.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  tests/plugin/sw_sanic/test_sanic.py
Labels: feature

#145 Cleaned up Tags
  README.md
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/kafka.py
  skywalking/client/http.py
  skywalking/decorators.py
  skywalking/plugins/sw_aiohttp.py
  skywalking/plugins/sw_celery.py
  skywalking/plugins/sw_django.py
  skywalking/plugins/sw_elasticsearch.py
  skywalking/plugins/sw_flask.py
  skywalking/plugins/sw_http_server.py
  skywalking/plugins/sw_kafka.py
  skywalking/plugins/sw_psycopg2.py
  skywalking/plugins/sw_pymongo.py
  skywalking/plugins/sw_pymysql.py
  skywalking/plugins/sw_pyramid.py
  skywalking/plugins/sw_rabbitmq.py
  skywalking/plugins/sw_redis.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_sanic.py
  skywalking/plugins/sw_tornado.py
  skywalking/plugins/sw_urllib3.py
  skywalking/plugins/sw_urllib_request.py
  skywalking/trace/span.py
  skywalking/trace/tags.py
  tests/plugin/sw_aiohttp/expected.data.yml
  tests/plugin/sw_django/expected.data.yml
  tests/plugin/sw_elasticsearch/expected.data.yml
  tests/plugin/sw_flask/expected.data.yml
  tests/plugin/sw_http/expected.data.yml
  tests/plugin/sw_http_wsgi/expected.data.yml
  tests/plugin/sw_kafka/expected.data.yml
  tests/plugin/sw_psycopg2/expected.data.yml
  tests/plugin/sw_pymongo/expected.data.yml
  tests/plugin/sw_pymysql/expected.data.yml
  tests/plugin/sw_pyramid/expected.data.yml
  tests/plugin/sw_rabbitmq/expected.data.yml
  tests/plugin/sw_redis/expected.data.yml
  tests/plugin/sw_requests/expected.data.yml
  tests/plugin/sw_sanic/expected.data.yml
  tests/plugin/sw_tornado/expected.data.yml
  tests/plugin/sw_urllib3/expected.data.yml
Labels: chore

#148 Remove the temporary gRPC log channel
  README.md
  docs/EnvVars.md
  docs/LogReporter.md
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/grpc_log.py
  skywalking/client/grpc.py
  skywalking/config.py
  skywalking/log/sw_logging.py
Labels: enhancement

#146 [plugin] add falcon plugin
  CHANGELOG.md
  docs/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/plugins/sw_falcon.py
  tests/plugin/sw_falcon/__init__.py
  tests/plugin/sw_falcon/docker-compose.yml
  tests/plugin/sw_falcon/expected.data.yml
  tests/plugin/sw_falcon/services/__init__.py
  tests/plugin/sw_falcon/services/consumer.py
  tests/plugin/sw_falcon/services/provider.py
  tests/plugin/sw_falcon/test_falcon.py
Labels: plugin

#150 [plugin] pymongo compatible with mongodb cluster
  skywalking/plugins/sw_pymongo.py
Labels: enhancement, plugin

#151 Fixes and tweaks to recent falcon plugin
  skywalking/plugins/sw_falcon.py
  skywalking/trace/tags.py
  tests/plugin/sw_falcon/expected.data.yml
Labels: bug, chore

#152 Remove HTTP basic auth credentials from log, stacktrace, segment
  CHANGELOG.md
  docs/EnvVars.md
  docs/LogReporter.md
  skywalking/agent/__init__.py
  skywalking/config.py
  skywalking/log/formatter.py
  skywalking/log/sw_logging.py
  skywalking/plugins/sw_requests.py
  skywalking/plugins/sw_urllib3.py
  skywalking/trace/span.py
  skywalking/utils/filter.py
Labels: enhancement

#149 Enable HTTP log reporting
  docs/LogReporter.md
  skywalking/agent/protocol/http.py
  skywalking/client/http.py
Labels: feature

#154 Enable Kafka log reporting
  docs/EnvVars.md
  docs/LogReporter.md
  skywalking/agent/protocol/kafka.py
  skywalking/client/http.py
  skywalking/client/kafka.py
  skywalking/config.py
  skywalking/log/sw_logging.py
  skywalking/plugins/sw_kafka.py
Labels: feature

#156 Support loading Python agent through sw-python CLI
  CHANGELOG.md
  README.md
  docs/CLI.md
  docs/EnvVars.md
  setup.py
  skywalking/bootstrap/__init__.py
  skywalking/bootstrap/cli/__init__.py
  skywalking/bootstrap/cli/sw_python.py
  skywalking/bootstrap/cli/utility/__init__.py
  skywalking/bootstrap/cli/utility/runner.py
  skywalking/bootstrap/loader/__init__.py
  skywalking/bootstrap/loader/sitecustomize.py
  skywalking/log/sw_logging.py
  sw_python/__init__.py
  sw_python/__main__.py
  sw_python/sw_python.py
Labels: feature, core

#158 Draft release notes for 0.7.0
  CHANGELOG.md
  setup.py
Labels: chore
