Repository apache/skywalking-python, pull requests merged in 2022-09, with the labels that each got.

#232 style: deal with B024 added to flake8 recently
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/trace/span.py
  tests/plugin/base.py
Labels: chore

#233 Confluent Kafka plugin
  docs/en/setup/Plugins.md
  skywalking/plugins/sw_confluent_kafka.py
Labels: plugin

#234 Fix text "PostgreSLQ" -> "PostgreSQL"
  skywalking/plugins/sw_asyncpg.py
  skywalking/plugins/sw_psycopg.py
  skywalking/plugins/sw_psycopg2.py
  tests/plugin/data/sw_psycopg/expected.data.yml
  tests/plugin/data/sw_psycopg2/expected.data.yml
Labels: bug

#235 Fix dead link due to the 'next' url change
  docs/en/setup/faq/How-to-use-with-uwsgi.md
Labels: documentation, chore

#236 refactor: hide some functions related to meter from users
  docs/en/setup/advanced/MeterReporter.md
  skywalking/meter/counter.py
  skywalking/meter/gauge.py
  skywalking/meter/histogram.py
  skywalking/meter/meter.py
  tests/unit/test_meter.py
Labels: enhancement
