Repository apache/skywalking-python, pull requests merged in 2022-01, with the labels that each got.

#177 Add missing ending quote
  docs/en/setup/Intrusive.md
Labels: documentation, chore

#179 updated deprecated configuration
  .lift/config.toml
Labels: chore

#178 Add plugin for mysqlclient
  docs/en/setup/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_mysqlclient.py
  tests/plugin/data/sw_mysqlclient/__init__.py
  tests/plugin/data/sw_mysqlclient/docker-compose.yml
  tests/plugin/data/sw_mysqlclient/expected.data.yml
  tests/plugin/data/sw_mysqlclient/services/__init__.py
  tests/plugin/data/sw_mysqlclient/services/consumer.py
  tests/plugin/data/sw_mysqlclient/services/provider.py
  tests/plugin/data/sw_mysqlclient/test_mysqlclient.py
Labels: feature, plugin
