Repository apache/skywalking-python, pull requests merged in 2022-02, with the labels that each got.

#182 Fix sw-rabbitmq TypeError when there are no headers
  skywalking/plugins/sw_rabbitmq.py
Labels: bug

#183 Fix agent bootup traceback not shown in sw-python CLI
  skywalking/bootstrap/cli/sw_python.py
  skywalking/bootstrap/loader/sitecustomize.py
Labels: chore

#181 Add plugin for FastAPI
  docs/en/setup/EnvVars.md
  docs/en/setup/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_fastapi.py
  tests/plugin/web/sw_fastapi/__init__.py
  tests/plugin/web/sw_fastapi/docker-compose.yml
  tests/plugin/web/sw_fastapi/expected.data.yml
  tests/plugin/web/sw_fastapi/services/__init__.py
  tests/plugin/web/sw_fastapi/services/consumer.py
  tests/plugin/web/sw_fastapi/services/provider.py
  tests/plugin/web/sw_fastapi/test_fastapi.py
Labels: feature, plugin

#186 Update mySQL plugin to support two different parameter keys.
  skywalking/plugins/sw_mysqlclient.py
  tests/plugin/web/sw_flask/docker-compose.yml
Labels: bug
