Repository apache/skywalking-python, pull requests merged in 2022-10, with the labels that each got.

#240 doc: new ability: metrics
  docs/README.md
Labels: documentation, chore

#242 Update span.py
  skywalking/trace/span.py
Labels: chore

#243 feat: add Kafka support to MeterReportService
  skywalking/agent/protocol/kafka.py
  skywalking/client/kafka.py
  skywalking/config.py
  tests/e2e/case/grpc/e2e.yaml
  tests/e2e/case/kafka/e2e.yaml
Labels: enhancement

#244 fix: Ignore websocket connections inside fastapi temporarily
  skywalking/plugins/sw_fastapi.py
Labels: bug
