Repository apache/skywalking-python, pull requests merged in 2022-03, with the labels that each got.

#188 Doc: add `how to use with uwsgi`
  docs/en/setup/faq/How-to-use-with-uwsgi.md
  docs/menu.yml
Labels: documentation

#190 The local log stack depth is not truncated
  skywalking/log/sw_logging.py
Labels: bug

#193 Fix typo that cause failure in loading user sitecustomize.py
  skywalking/bootstrap/loader/sitecustomize.py
Labels: bug

#195 Drop support for Flask 1.x due to EOL & Jinja2 issue
  docs/en/setup/Plugins.md
  skywalking/plugins/sw_flask.py
Labels: test, plugin

#197 Update agent docs, changelogs and PR template.
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
  docs/en/setup/CLI.md
  docs/en/setup/EnvVars.md
  docs/en/setup/Intrusive.md
Labels: documentation, chore

#194 Fix Python shown as UNKNOWN language in OAP
  skywalking/client/grpc.py
  skywalking/client/http.py
  skywalking/client/kafka.py
Labels: bug

#196 Fix logging level not properly set according to config
  skywalking/loggings.py
Labels: bug

#198 Fix the properties are not set correctly
  skywalking/client/http.py
Labels: bug
