Repository apache/skywalking-python, pull requests merged in 2022-07, with the labels that each got.

#216 Fix typo in docker/Makefile
  docker/Makefile
Labels: chore

#217 Update UI repository link in PR template
  .github/PULL_REQUEST_TEMPLATE
Labels: chore

#214 Add plugin for bottle
  CHANGELOG.md
  docs/en/setup/EnvVars.md
  docs/en/setup/Plugins.md
  requirements.txt
  skywalking/__init__.py
  skywalking/config.py
  skywalking/plugins/sw_bottle.py
  tests/plugin/web/sw_bottle/__init__.py
  tests/plugin/web/sw_bottle/docker-compose.yml
  tests/plugin/web/sw_bottle/expected.data.yml
  tests/plugin/web/sw_bottle/services/__init__.py
  tests/plugin/web/sw_bottle/services/consumer.py
  tests/plugin/web/sw_bottle/services/provider.py
  tests/plugin/web/sw_bottle/test_bottle.py
Labels: plugin

#219 Draft release 0.8.0
  CHANGELOG.md
  setup.py
Labels: documentation, chore

#220 Migrate license checker to license-eye and adjust the release script
  .licenserc.yaml
  Makefile
  tools/check-license-header.py
Labels: chore

#222 doc: add How to test locally
  .dockerignore
  docs/en/setup/faq/How-to-test-locally.md
Labels: documentation

#223 Move test guide to contribution and add to doc menu
  docs/en/contribution/How-to-test-locally.md
  docs/menu.yml
Labels: documentation

#225 Fix RabbitMQ basic_get(), Makefile missing packages
  Makefile
  skywalking/plugins/sw_rabbitmq.py
Labels: bug

#226 fix again for BlockingChannel.basic_get()
  skywalking/plugins/sw_rabbitmq.py
Labels: bug

#227 Fix tornado socket == None
  skywalking/plugins/sw_tornado.py
Labels: bug
