Repository apache/skywalking-python, pull requests merged in 2022-11, with the labels that each got.

#249 Introduce Poetry and bump up e2e
  .dockerignore
  .github/PULL_REQUEST_TEMPLATE
  .github/workflows/CI.yaml
  .gitignore
  .licenserc.yaml
  Makefile
  README.md
  docker/Makefile
  docs/README.md
  docs/en/contribution/Developer.md
  docs/en/contribution/How-to-develop-plugin.md
  docs/en/contribution/How-to-release-docker.md
  docs/en/contribution/How-to-release.md
  docs/en/contribution/How-to-test-locally.md
  docs/en/contribution/How-to-test-plugin.md
  docs/en/setup/Container.md
  docs/en/setup/Installation.md
  docs/en/setup/advanced/MeterReporter.md
  docs/en/setup/faq/How-to-build-from-sources.md
  docs/menu.yml
  poetry.lock
  poetry.toml
  pyproject.toml
  requirements-style.txt
  requirements.txt
  setup.cfg
  setup.py
  skywalking/meter/pvm/data_source.py
  skywalking/plugins/sw_kafka.py
  tests/e2e/base/Dockerfile.e2e
  tests/e2e/base/docker-compose.base.yml
  tests/e2e/base/provider/provider.py
  tests/e2e/base/tmp/application.yml
  tests/e2e/base/tmp/python.yaml
  tests/e2e/case/expected/logs-list.yml
  tests/e2e/case/expected/service-instance.yml
  tests/e2e/case/expected/trace-artist-detail.yml
  tests/e2e/case/expected/traces-list.yml
  tests/e2e/case/grpc/e2e.yaml
  tests/e2e/case/http/e2e.yaml
  tests/e2e/case/kafka/e2e.yaml
  tests/e2e/script/env
  tests/e2e/script/prepare/install-yq.sh
  tests/plugin/Dockerfile.plugin
  tests/plugin/docker-compose.base.yml
  tools/env/build_requirements_linux.sh
  tools/env/build_requirements_windows.bat
  tools/env/setup_linux.sh
  tools/env/setup_windows.ps1
  tools/grpc_code_gen.py
  tools/plugin_doc_gen.py
Labels: documentation, chore, test

#251 Enable E2E batch mode and pin Infra-E2E version
  .github/workflows/CI.yaml
Labels: chore, test

#250 Doc for greenlet profiler
  docs/en/profiling/profiling.md
Labels: documentation

#252 Add all changelogs since 0.8.0 release
  CHANGELOG.md
Labels: chore

#253 Cover grpcio tools codegen changes
  CHANGELOG.md
  Makefile
  poetry.lock
  tools/grpc_code_gen.py
Labels: chore
