Repository apache/skywalking-python, pull requests merged in 2023-04, with the labels that each got.

#297 [feat]Build multi-architecture Docker images for Python agent
  .github/workflows/publish-docker.yaml
  CHANGELOG.md
  docker/Dockerfile
  docker/Makefile
Labels: feature

#299 Fix sw8 loss when use aiohttp.
  CHANGELOG.md
  skywalking/plugins/sw_aiohttp.py
Labels: bug

#300 Fix high CPU usage
  CHANGELOG.md
  skywalking/agent/__init__.py
Labels: bug

#303 Adjust Bitnami Kafka image and use Kraft in E2E
  CHANGELOG.md
  tests/e2e/base/docker-compose.base.yml
  tests/e2e/case/kafka/gunicorn/docker-compose.kafka.gunicorn.yaml
  tests/e2e/case/kafka/single/docker-compose.kafka.single.yaml
  tests/e2e/case/kafka/uwsgi/docker-compose.kafka.uwsgi.yaml
Labels: test

#302 Optimize loguru reporter plugin
  CHANGELOG.md
  docs/en/setup/Plugins.md
  skywalking/plugins/sw_loguru.py
Labels: bug, enhancement
