Repository apache/skywalking-python, pull requests merged in 2023-01, with the labels that each got.

#263 Enhance redis plugin to adapt Virtual Cache
  CHANGELOG.md
  skywalking/plugins/sw_redis.py
  skywalking/trace/tags.py
  tests/plugin/data/sw_redis/expected.data.yml
Labels: enhancement

#265 Fix dev dependency version constraint for Apple M1
  poetry.lock
  pyproject.toml
Labels: chore, dependencies

#266 Add hbase happy plugin
  CHANGELOG.md
  docs/en/setup/Plugins.md
  poetry.lock
  pyproject.toml
  skywalking/__init__.py
  skywalking/plugins/sw_happybase.py
  tests/plugin/data/sw_happybase/__init__.py
  tests/plugin/data/sw_happybase/docker-compose.yml
  tests/plugin/data/sw_happybase/expected.data.yml
  tests/plugin/data/sw_happybase/services/__init__.py
  tests/plugin/data/sw_happybase/services/consumer.py
  tests/plugin/data/sw_happybase/test_happybase.py
Labels: plugin

#270 Disable Sonatype lift bind_all_interface check
  .lift/config.toml
Labels: chore

#267 Fix sw_logging (log reporter) potentially throw exception leading to traceback confusion
  CHANGELOG.md
  skywalking/log/sw_logging.py
Labels: bug

#268 Use slim in plugin tests
  .github/workflows/CI.yaml
  CHANGELOG.md
  Makefile
  docs/en/setup/Plugins.md
  skywalking/plugins/sw_mysqlclient.py
  tests/plugin/Dockerfile.plugin
  tests/plugin/conftest.py
  tests/plugin/data/sw_mysqlclient/docker-compose.yml
Labels: test

#271 Add tables to show agent features and clean up configs
  CHANGELOG.md
  README.md
  docs/README.md
  docs/en/setup/EnvVars.md
  docs/en/setup/Installation.md
  docs/menu.yml
  skywalking/config.py
  skywalking/meter/meter_service.py
Labels: documentation, enhancement, feature

#272 Remove meaningless traceid in log dashboard
  CHANGELOG.md
  skywalking/log/sw_logging.py
Labels: bug

#273 Remove configuration debts before we release 1.0.0
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
  Makefile
  README.md
  docs/README.md
  docs/en/contribution/How-to-develop-plugin.md
  docs/en/setup/CLI.md
  docs/en/setup/Configuration.md
  docs/en/setup/Container.md
  docs/en/setup/EnvVars.md
  docs/en/setup/Installation.md
  docs/en/setup/Intrusive.md
  docs/en/setup/Plugins.md
  docs/en/setup/advanced/LogReporter.md
  docs/en/setup/faq/How-to-disable-plugin.md
  docs/menu.yml
  skywalking/agent/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
  skywalking/bootstrap/loader/sitecustomize.py
  skywalking/client/grpc.py
  skywalking/client/http.py
  skywalking/client/kafka.py
  skywalking/config.py
  skywalking/profile/profile_context.py
  tests/e2e/base/docker-compose.base.yml
  tests/e2e/case/grpc/docker-compose.yml
  tests/e2e/case/http/docker-compose.yml
  tests/e2e/case/kafka/docker-compose.yml
  tests/e2e/case/profiling/greenlet/docker-compose.yml
  tests/e2e/case/profiling/threading/docker-compose.yml
  tests/plugin/data/sw_elasticsearch/docker-compose.yml
  tests/plugin/data/sw_happybase/docker-compose.yml
  tests/plugin/data/sw_kafka/docker-compose.yml
  tests/plugin/data/sw_mysqlclient/docker-compose.yml
  tests/plugin/data/sw_psycopg/docker-compose.yml
  tests/plugin/data/sw_psycopg2/docker-compose.yml
  tests/plugin/data/sw_pymongo/docker-compose.yml
  tests/plugin/data/sw_pymysql/docker-compose.yml
  tests/plugin/data/sw_rabbitmq/docker-compose.yml
  tests/plugin/data/sw_redis/docker-compose.yml
  tests/plugin/docker-compose.base.yml
  tests/plugin/http/sw_aiohttp/docker-compose.yml
  tests/plugin/http/sw_http/docker-compose.yml
  tests/plugin/http/sw_http_wsgi/docker-compose.yml
  tests/plugin/http/sw_requests/docker-compose.yml
  tests/plugin/http/sw_urllib3/docker-compose.yml
  tests/plugin/http/sw_websockets/docker-compose.yml
  tests/plugin/web/sw_bottle/docker-compose.yml
  tests/plugin/web/sw_django/docker-compose.yml
  tests/plugin/web/sw_falcon/docker-compose.yml
  tests/plugin/web/sw_fastapi/docker-compose.yml
  tests/plugin/web/sw_flask/docker-compose.yml
  tests/plugin/web/sw_pyramid/docker-compose.yml
  tests/plugin/web/sw_sanic/docker-compose.yml
  tests/plugin/web/sw_tornado/docker-compose.yml
  tools/config_doc_gen.py
  tools/plugin_doc_gen.py
Labels: bug, documentation, enhancement, chore
