Repository apache/skywalking-python, pull requests merged in 2023-02, with the labels that each got.

#275 Add namespace suffix to service name
  CHANGELOG.md
  Makefile
  docs/en/setup/Configuration.md
  skywalking/config.py
  tests/e2e/base/docker-compose.base.yml
  tests/e2e/case/expected/service.yml
  tests/e2e/case/expected/trace-artist-detail.yml
  tests/e2e/case/grpc/e2e.yaml
  tests/e2e/case/http/e2e.yaml
  tests/e2e/case/kafka/e2e.yaml
Labels: enhancement

#277 Add kafka prefix to kakfa topic names
  CHANGELOG.md
  docs/en/setup/Configuration.md
  skywalking/config.py
  tests/e2e/case/kafka/docker-compose.yml
Labels: feature

#279 Periodically report instance properties
  CHANGELOG.md
  Makefile
  docs/en/setup/Configuration.md
  skywalking/agent/__init__.py
  skywalking/agent/protocol/__init__.py
  skywalking/agent/protocol/grpc.py
  skywalking/agent/protocol/http.py
  skywalking/agent/protocol/kafka.py
  skywalking/client/__init__.py
  skywalking/client/grpc.py
  skywalking/client/http.py
  skywalking/client/kafka.py
  skywalking/config.py
  tests/e2e/base/docker-compose.base.yml
  tests/e2e/case/expected/service-instance.yml
  tools/config_doc_gen.py
Labels: bug, core

#281 Fix sw_logging when `Logger.disabled` is true
  CHANGELOG.md
  skywalking/log/sw_logging.py
Labels: bug

#283 Add Httpx plugin
  CHANGELOG.md
  docs/en/contribution/Developer.md
  docs/en/contribution/How-to-develop-plugin.md
  docs/en/contribution/How-to-test-locally.md
  docs/en/setup/Plugins.md
  poetry.lock
  pyproject.toml
  skywalking/__init__.py
  skywalking/plugins/sw_httpx.py
  tests/plugin/http/sw_httpx/__init__.py
  tests/plugin/http/sw_httpx/docker-compose.yml
  tests/plugin/http/sw_httpx/expected.data.yml
  tests/plugin/http/sw_httpx/services/__init__.py
  tests/plugin/http/sw_httpx/services/consumer.py
  tests/plugin/http/sw_httpx/services/provider.py
  tests/plugin/http/sw_httpx/test_httpx.py
Labels: plugin

#285 Add support for python 3.11
  .github/workflows/CI.yaml
  CHANGELOG.md
  docker/Makefile
  docs/en/setup/Container.md
  docs/en/setup/Plugins.md
  poetry.lock
  pyproject.toml
  skywalking/plugins/sw_bottle.py
  skywalking/plugins/sw_falcon.py
  skywalking/plugins/sw_psycopg.py
Labels: dependencies

#289 Draft release v1.0.0
  CHANGELOG.md
  pyproject.toml
Labels: documentation

#291 Fix Docker build missing required ARG
  Makefile
  docker/Makefile
Labels: bug
