Repository apache/skywalking-python, pull requests merged in 2023-11, with the labels that each got.

#326 loose restrict of greenlet (#3)
  poetry.lock
  pyproject.toml
  skywalking/profile/profile_context.py
  tests/e2e/base/Dockerfile.e2e
  tests/e2e/case/profiling/greenlet/start_gevent.sh
  tests/plugin/web/sw_flask/docker-compose.yml
Labels: enhancement

#323 Add support printing TID to logs
  CHANGELOG.md
  docs/en/setup/advanced/LogReporter.md
  skywalking/agent/__init__.py
  skywalking/log/sw_logging.py
Labels: feature

#328 Fix psutil dockerfile version constraint
  CHANGELOG.md
  docker/Dockerfile
Labels: bug

#329 Change from pkg_resources to importlib metadata
  CHANGELOG.md
  skywalking/plugins/__init__.py
  tools/grpc_code_gen.py
Labels: dependencies
