Repository apache/skywalking-python, pull requests merged in 2024-11, with the labels that each got.

#356 Drop support for 3.7 and fix tests
  .github/workflows/CI.yaml
  Makefile
  README.md
  docker/Makefile
  docs/en/contribution/Developer.md
  docs/en/setup/Container.md
  docs/en/setup/Installation.md
  docs/en/setup/Plugins.md
  docs/en/setup/faq/How-to-build-from-sources.md
  poetry.lock
  pyproject.toml
  skywalking/plugins/sw_aiohttp.py
  tests/plugin/data/sw_elasticsearch/docker-compose.yml
  tests/plugin/data/sw_kafka/docker-compose.yml
  tests/plugin/data/sw_mysqlclient/docker-compose.yml
  tests/plugin/data/sw_rabbitmq/docker-compose.yml
Labels: test

#355 Fix TestClient for fastapi cause the req.client None error
  CHANGELOG.md
  skywalking/plugins/sw_fastapi.py
Labels: bug

#357 Feat sampling service
  CHANGELOG.md
  docs/en/contribution/CodingStyle.md
  docs/en/setup/Configuration.md
  skywalking/agent/__init__.py
  skywalking/config.py
  skywalking/sampling/__init__.py
  skywalking/sampling/sampling_service.py
  skywalking/trace/context.py
  tests/unit/test_sampling.py
Labels: feature
